# Generated by Django 5.2 on 2025-04-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedbookmarks",
            name="is_broken",
        ),
    ]
